DROP TABLE IF EXISTS data_user;
DROP TABLE IF EXISTS drug_report;
DROP TABLE IF EXISTS product_active_substance_map; 
DROP TABLE IF EXISTS active_substance;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS person_in_tenant;
DROP TABLE IF EXISTS tenant;
DROP TABLE IF EXISTS person;
-- DROP TYPE IF EXISTS person_type;
